pokemon = [
    {"Number": 0, "Name": "MissingNo", "Type1": "", "Type2": "", "HP": 0, "Attack": 0, "Defense": 0, "Speed": 0, "Special": 0},
    {"Number": 1, "Name": "Bulbasaur", "Type1": "Grass", "Type2": "Poison", "HP": 45, "Attack": 49, "Defense": 49, "Speed": 45, "Special": 65},
    {"Number": 2, "Name": "Ivysaur", "Type1": "Grass", "Type2": "Poison", "HP": 60, "Attack": 62, "Defense": 63, "Speed": 60, "Special": 80},
    {"Number": 3, "Name": "Venusaur", "Type1": "Grass", "Type2": "Poison", "HP": 80, "Attack": 82, "Defense": 83, "Speed": 80, "Special": 100},
    {"Number": 4, "Name": "Charmander", "Type1": "Fire", "Type2": "", "HP": 39, "Attack": 52, "Defense": 43, "Speed": 65, "Special": 50},
    {"Number": 5, "Name": "Charmeleon", "Type1": "Fire", "Type2": "", "HP": 58, "Attack": 64, "Defense": 58, "Speed": 80, "Special": 65},
    {"Number": 6, "Name": "Charizard", "Type1": "Fire", "Type2": "Flying", "HP": 78, "Attack": 84, "Defense": 78, "Speed": 100, "Special": 85},
    {"Number": 7, "Name": "Squirtle", "Type1": "Water", "Type2": "", "HP": 44, "Attack": 48, "Defense": 65, "Speed": 43, "Special": 50},
    {"Number": 8, "Name": "Wartortle", "Type1": "Water", "Type2": "", "HP": 59, "Attack": 63, "Defense": 80, "Speed": 58, "Special": 65},
    {"Number": 9, "Name": "Blastoise", "Type1": "Water", "Type2": "", "HP": 79, "Attack": 83, "Defense": 100, "Speed": 78, "Special": 85},
    {"Number": 10, "Name": "Caterpie", "Type1": "Bug", "Type2": "", "HP": 45, "Attack": 30, "Defense": 35, "Speed": 45, "Special": 20},
    {"Number": 11, "Name": "Metapod", "Type1": "Bug", "Type2": "", "HP": 50, "Attack": 20, "Defense": 55, "Speed": 30, "Special": 25},
    {"Number": 12, "Name": "Butterfree", "Type1": "Bug", "Type2": "Flying", "HP": 60, "Attack": 45, "Defense": 50, "Speed": 70, "Special": 80},
    {"Number": 13, "Name": "Weedle", "Type1": "Bug", "Type2": "Poison", "HP": 40, "Attack": 35, "Defense": 30, "Speed": 50, "Special": 20},
    {"Number": 14, "Name": "Kakuna", "Type1": "Bug", "Type2": "Poison", "HP": 45, "Attack": 25, "Defense": 50, "Speed": 35, "Special": 25},
    {"Number": 15, "Name": "Beedrill", "Type1": "Bug", "Type2": "Poison", "HP": 65, "Attack": 80, "Defense": 40, "Speed": 75, "Special": 45},
    {"Number": 16, "Name": "Pidgey", "Type1": "Normal", "Type2": "Flying", "HP": 40, "Attack": 45, "Defense": 40, "Speed": 56, "Special": 35},
    {"Number": 17, "Name": "Pidgeotto", "Type1": "Normal", "Type2": "Flying", "HP": 63, "Attack": 60, "Defense": 55, "Speed": 71, "Special": 50},
    {"Number": 18, "Name": "Pidgeot", "Type1": "Normal", "Type2": "Flying", "HP": 83, "Attack": 80, "Defense": 75, "Speed": 91, "Special": 70},
    {"Number": 19, "Name": "Rattata", "Type1": "Normal", "Type2": "", "HP": 30, "Attack": 56, "Defense": 35, "Speed": 72, "Special": 25},
    {"Number": 20, "Name": "Raticate", "Type1": "Normal", "Type2": "", "HP": 55, "Attack": 81, "Defense": 60, "Speed": 97, "Special": 50},
    {"Number": 21, "Name": "Spearow", "Type1": "Normal", "Type2": "Flying", "HP": 40, "Attack": 60, "Defense": 30, "Speed": 70, "Special": 31},
    {"Number": 22, "Name": "Fearow", "Type1": "Normal", "Type2": "Flying", "HP": 65, "Attack": 90, "Defense": 65, "Speed": 100, "Special": 61},
    {"Number": 23, "Name": "Ekans", "Type1": "Poison", "Type2": "", "HP": 35, "Attack": 60, "Defense": 44, "Speed": 55, "Special": 40},
    {"Number": 24, "Name": "Arbok", "Type1": "Poison", "Type2": "", "HP": 60, "Attack": 85, "Defense": 69, "Speed": 80, "Special": 65},
    {"Number": 25, "Name": "Pikachu", "Type1": "Electric", "Type2": "", "HP": 35, "Attack": 55, "Defense": 30, "Speed": 90, "Special": 50},
    {"Number": 26, "Name": "Raichu", "Type1": "Electric", "Type2": "", "HP": 60, "Attack": 90, "Defense": 55, "Speed": 100, "Special": 90},
    {"Number": 27, "Name": "Sandshrew", "Type1": "Ground", "Type2": "", "HP": 50, "Attack": 75, "Defense": 85, "Speed": 40, "Special": 30},
    {"Number": 28, "Name": "Sandslash", "Type1": "Ground", "Type2": "", "HP": 75, "Attack": 100, "Defense": 110, "Speed": 65, "Special": 55},
    {"Number": 29, "Name": "NidoranW", "Type1": "Poison", "Type2": "", "HP": 55, "Attack": 47, "Defense": 52, "Speed": 41, "Special": 40},
    {"Number": 30, "Name": "Nidorina", "Type1": "Poison", "Type2": "", "HP": 70, "Attack": 62, "Defense": 67, "Speed": 56, "Special": 55},
    {"Number": 31, "Name": "Nidoqueen", "Type1": "Poison", "Type2": "Ground", "HP": 90, "Attack": 82, "Defense": 87, "Speed": 76, "Special": 75},
    {"Number": 32, "Name": "NidoranM", "Type1": "Poison", "Type2": "", "HP": 46, "Attack": 57, "Defense": 40, "Speed": 50, "Special": 40},
    {"Number": 33, "Name": "Nidorino", "Type1": "Poison", "Type2": "", "HP": 61, "Attack": 72, "Defense": 57, "Speed": 65, "Special": 55},
    {"Number": 34, "Name": "Nidoking", "Type1": "Poison", "Type2": "Ground", "HP": 81, "Attack": 92, "Defense": 77, "Speed": 85, "Special": 75},
    {"Number": 35, "Name": "Clefairy", "Type1": "Normal", "Type2": "", "HP": 70, "Attack": 45, "Defense": 48, "Speed": 35, "Special": 60},
    {"Number": 36, "Name": "Clefable", "Type1": "Normal", "Type2": "", "HP": 95, "Attack": 70, "Defense": 73, "Speed": 60, "Special": 85},
    {"Number": 37, "Name": "Vulpix", "Type1": "Fire", "Type2": "", "HP": 38, "Attack": 41, "Defense": 40, "Speed": 65, "Special": 65},
    {"Number": 38, "Name": "Ninetales", "Type1": "Fire", "Type2": "", "HP": 73, "Attack": 76, "Defense": 75, "Speed": 100, "Special": 100},
    {"Number": 39, "Name": "Jigglypuff", "Type1": "Normal", "Type2": "", "HP": 115, "Attack": 45, "Defense": 20, "Speed": 20, "Special": 25},
    {"Number": 40, "Name": "Wigglytuff", "Type1": "Normal", "Type2": "", "HP": 140, "Attack": 70, "Defense": 45, "Speed": 45, "Special": 50},
    {"Number": 41, "Name": "Zubat", "Type1": "Poison", "Type2": "Flying", "HP": 40, "Attack": 45, "Defense": 35, "Speed": 55, "Special": 40},
    {"Number": 42, "Name": "Golbat", "Type1": "Poison", "Type2": "Flying", "HP": 75, "Attack": 80, "Defense": 70, "Speed": 90, "Special": 75},
    {"Number": 43, "Name": "Oddish", "Type1": "Grass", "Type2": "Poison", "HP": 45, "Attack": 50, "Defense": 55, "Speed": 30, "Special": 75},
    {"Number": 44, "Name": "Gloom", "Type1": "Grass", "Type2": "Poison", "HP": 60, "Attack": 65, "Defense": 70, "Speed": 40, "Special": 85},
    {"Number": 45, "Name": "Vileplume", "Type1": "Grass", "Type2": "Poison", "HP": 75, "Attack": 80, "Defense": 85, "Speed": 50, "Special": 100},
    {"Number": 46, "Name": "Paras", "Type1": "Bug", "Type2": "Grass", "HP": 35, "Attack": 70, "Defense": 55, "Speed": 25, "Special": 55},
    {"Number": 47, "Name": "Parasect", "Type1": "Bug", "Type2": "Grass", "HP": 60, "Attack": 95, "Defense": 80, "Speed": 30, "Special": 80},
    {"Number": 48, "Name": "Venonat", "Type1": "Bug", "Type2": "Poison", "HP": 60, "Attack": 55, "Defense": 50, "Speed": 45, "Special": 40},
    {"Number": 49, "Name": "Venomoth", "Type1": "Bug", "Type2": "Poison", "HP": 70, "Attack": 65, "Defense": 60, "Speed": 90, "Special": 90},
    {"Number": 50, "Name": "Diglett", "Type1": "Ground", "Type2": "", "HP": 10, "Attack": 55, "Defense": 25, "Speed": 95, "Special": 45},
    {"Number": 51, "Name": "Dugtrio", "Type1": "Ground", "Type2": "", "HP": 35, "Attack": 80, "Defense": 50, "Speed": 120, "Special": 70},
    {"Number": 52, "Name": "Meowth", "Type1": "Normal", "Type2": "", "HP": 40, "Attack": 45, "Defense": 35, "Speed": 90, "Special": 40},
    {"Number": 53, "Name": "Persian", "Type1": "Normal", "Type2": "", "HP": 65, "Attack": 70, "Defense": 60, "Speed": 115, "Special": 65},
    {"Number": 54, "Name": "Psyduck", "Type1": "Water", "Type2": "", "HP": 50, "Attack": 52, "Defense": 48, "Speed": 55, "Special": 50},
    {"Number": 55, "Name": "Golduck", "Type1": "Water", "Type2": "", "HP": 80, "Attack": 82, "Defense": 78, "Speed": 85, "Special": 80},
    {"Number": 56, "Name": "Mankey", "Type1": "Fighting", "Type2": "", "HP": 40, "Attack": 80, "Defense": 35, "Speed": 70, "Special": 35},
    {"Number": 57, "Name": "Primeape", "Type1": "Fighting", "Type2": "", "HP": 65, "Attack": 105, "Defense": 60, "Speed": 95, "Special": 60},
    {"Number": 58, "Name": "Growlithe", "Type1": "Fire", "Type2": "", "HP": 55, "Attack": 70, "Defense": 45, "Speed": 60, "Special": 50},
    {"Number": 59, "Name": "Arcanine", "Type1": "Fire", "Type2": "", "HP": 90, "Attack": 110, "Defense": 80, "Speed": 95, "Special": 80},
    {"Number": 60, "Name": "Poliwag", "Type1": "Water", "Type2": "", "HP": 40, "Attack": 50, "Defense": 40, "Speed": 90, "Special": 40},
    {"Number": 61, "Name": "Poliwhirl", "Type1": "Water", "Type2": "", "HP": 65, "Attack": 65, "Defense": 65, "Speed": 90, "Special": 50},
    {"Number": 62, "Name": "Poliwrath", "Type1": "Water", "Type2": "Fighting", "HP": 90, "Attack": 85, "Defense": 95, "Speed": 70, "Special": 70},
    {"Number": 63, "Name": "Abra", "Type1": "Psychic", "Type2": "", "HP": 25, "Attack": 20, "Defense": 15, "Speed": 90, "Special": 105},
    {"Number": 64, "Name": "Kadabra", "Type1": "Psychic", "Type2": "", "HP": 40, "Attack": 35, "Defense": 30, "Speed": 105, "Special": 120},
    {"Number": 65, "Name": "Alakazam", "Type1": "Psychic", "Type2": "", "HP": 55, "Attack": 50, "Defense": 45, "Speed": 120, "Special": 135},
    {"Number": 66, "Name": "Machop", "Type1": "Fighting", "Type2": "", "HP": 70, "Attack": 80, "Defense": 50, "Speed": 35, "Special": 35},
    {"Number": 67, "Name": "Machoke", "Type1": "Fighting", "Type2": "", "HP": 80, "Attack": 100, "Defense": 70, "Speed": 45, "Special": 50},
    {"Number": 68, "Name": "Machamp", "Type1": "Fighting", "Type2": "", "HP": 90, "Attack": 130, "Defense": 80, "Speed": 55, "Special": 65},
    {"Number": 69, "Name": "Bellsprout", "Type1": "Grass", "Type2": "Poison", "HP": 50, "Attack": 75, "Defense": 35, "Speed": 40, "Special": 70},
    {"Number": 70, "Name": "Weepinbell", "Type1": "Grass", "Type2": "Poison", "HP": 65, "Attack": 90, "Defense": 50, "Speed": 55, "Special": 85},
    {"Number": 71, "Name": "Victreebel", "Type1": "Grass", "Type2": "Poison", "HP": 80, "Attack": 105, "Defense": 65, "Speed": 70, "Special": 100},
    {"Number": 72, "Name": "Tentacool", "Type1": "Water", "Type2": "Poison", "HP": 40, "Attack": 40, "Defense": 35, "Speed": 70, "Special": 100},
    {"Number": 73, "Name": "Tentacruel", "Type1": "Water", "Type2": "Poison", "HP": 80, "Attack": 70, "Defense": 65, "Speed": 100, "Special": 120},
    {"Number": 74, "Name": "Geodude", "Type1": "Rock", "Type2": "Ground", "HP": 40, "Attack": 80, "Defense": 100, "Speed": 20, "Special": 30},
    {"Number": 75, "Name": "Graveler", "Type1": "Rock", "Type2": "Ground", "HP": 55, "Attack": 95, "Defense": 115, "Speed": 35, "Special": 45},
    {"Number": 76, "Name": "Golem", "Type1": "Rock", "Type2": "Ground", "HP": 80, "Attack": 110, "Defense": 130, "Speed": 45, "Special": 55},
    {"Number": 77, "Name": "Ponyta", "Type1": "Fire", "Type2": "", "HP": 50, "Attack": 85, "Defense": 55, "Speed": 90, "Special": 65},
    {"Number": 78, "Name": "Rapidash", "Type1": "Fire", "Type2": "", "HP": 65, "Attack": 100, "Defense": 70, "Speed": 105, "Special": 80},
    {"Number": 79, "Name": "Slowpoke", "Type1": "Water", "Type2": "Psychic", "HP": 90, "Attack": 65, "Defense": 65, "Speed": 15, "Special": 40},
    {"Number": 80, "Name": "Slowbro", "Type1": "Water", "Type2": "Psychic", "HP": 95, "Attack": 75, "Defense": 110, "Speed": 30, "Special": 80},
    {"Number": 81, "Name": "Magnemite", "Type1": "Electric", "Type2": "", "HP": 25, "Attack": 35, "Defense": 70, "Speed": 45, "Special": 95},
    {"Number": 82, "Name": "Magneton", "Type1": "Electric", "Type2": "", "HP": 50, "Attack": 60, "Defense": 95, "Speed": 70, "Special": 120},
    {"Number": 83, "Name": "Farfetch'd", "Type1": "Normal", "Type2": "Flying", "HP": 52, "Attack": 65, "Defense": 55, "Speed": 60, "Special": 58},
    {"Number": 84, "Name": "Doduo", "Type1": "Normal", "Type2": "Flying", "HP": 35, "Attack": 85, "Defense": 45, "Speed": 75, "Special": 35},
    {"Number": 85, "Name": "Dodrio", "Type1": "Normal", "Type2": "Flying", "HP": 60, "Attack": 110, "Defense": 70, "Speed": 100, "Special": 60},
    {"Number": 86, "Name": "Seel", "Type1": "Water", "Type2": "", "HP": 65, "Attack": 45, "Defense": 55, "Speed": 45, "Special": 70},
    {"Number": 87, "Name": "Dewgong", "Type1": "Water", "Type2": "Ice", "HP": 90, "Attack": 70, "Defense": 80, "Speed": 70, "Special": 95},
    {"Number": 88, "Name": "Grimer", "Type1": "Poison", "Type2": "", "HP": 80, "Attack": 80, "Defense": 50, "Speed": 25, "Special": 40},
    {"Number": 89, "Name": "Muk", "Type1": "Poison", "Type2": "", "HP": 105, "Attack": 105, "Defense": 75, "Speed": 50, "Special": 65},
    {"Number": 90, "Name": "Shellder", "Type1": "Water", "Type2": "", "HP": 30, "Attack": 65, "Defense": 100, "Speed": 40, "Special": 45},
    {"Number": 91, "Name": "Cloyster", "Type1": "Water", "Type2": "Ice", "HP": 50, "Attack": 95, "Defense": 180, "Speed": 70, "Special": 85},
    {"Number": 92, "Name": "Gastly", "Type1": "Ghost", "Type2": "Poison", "HP": 30, "Attack": 35, "Defense": 30, "Speed": 80, "Special": 100},
    {"Number": 93, "Name": "Haunter", "Type1": "Ghost", "Type2": "Poison", "HP": 45, "Attack": 50, "Defense": 45, "Speed": 95, "Special": 115},
    {"Number": 94, "Name": "Gengar", "Type1": "Ghost", "Type2": "Poison", "HP": 60, "Attack": 65, "Defense": 60, "Speed": 110, "Special": 130},
    {"Number": 95, "Name": "Onix", "Type1": "Rock", "Type2": "Ground", "HP": 35, "Attack": 45, "Defense": 160, "Speed": 70, "Special": 30},
    {"Number": 96, "Name": "Drowzee", "Type1": "Psychic", "Type2": "", "HP": 60, "Attack": 48, "Defense": 45, "Speed": 42, "Special": 90},
    {"Number": 97, "Name": "Hypno", "Type1": "Psychic", "Type2": "", "HP": 85, "Attack": 73, "Defense": 70, "Speed": 67, "Special": 115},
    {"Number": 98, "Name": "Krabby", "Type1": "Water", "Type2": "", "HP": 30, "Attack": 105, "Defense": 90, "Speed": 50, "Special": 25},
    {"Number": 99, "Name": "Kingler", "Type1": "Water", "Type2": "", "HP": 55, "Attack": 130, "Defense": 115, "Speed": 75, "Special": 50},
    {"Number": 100, "Name": "Voltorb", "Type1": "Electric", "Type2": "", "HP": 40, "Attack": 30, "Defense": 50, "Speed": 100, "Special": 55},
    {"Number": 101, "Name": "Electrode", "Type1": "Electric", "Type2": "", "HP": 60, "Attack": 50, "Defense": 70, "Speed": 140, "Special": 80},
    {"Number": 102, "Name": "Exeggcute", "Type1": "Grass", "Type2": "Psychic", "HP": 60, "Attack": 40, "Defense": 80, "Speed": 40, "Special": 60},
    {"Number": 103, "Name": "Exeggutor", "Type1": "Grass", "Type2": "Psychic", "HP": 95, "Attack": 95, "Defense": 85, "Speed": 55, "Special": 125},
    {"Number": 104, "Name": "Cubone", "Type1": "Ground", "Type2": "", "HP": 50, "Attack": 50, "Defense": 95, "Speed": 35, "Special": 40},
    {"Number": 105, "Name": "Marowak", "Type1": "Ground", "Type2": "", "HP": 60, "Attack": 80, "Defense": 110, "Speed": 45, "Special": 50},
    {"Number": 106, "Name": "Hitmonlee", "Type1": "Fighting", "Type2": "", "HP": 50, "Attack": 120, "Defense": 53, "Speed": 87, "Special": 35},
    {"Number": 107, "Name": "Hitmonchan", "Type1": "Fighting", "Type2": "", "HP": 50, "Attack": 105, "Defense": 79, "Speed": 76, "Special": 35},
    {"Number": 108, "Name": "Lickitung", "Type1": "Normal", "Type2": "", "HP": 90, "Attack": 55, "Defense": 75, "Speed": 30, "Special": 60},
    {"Number": 109, "Name": "Koffing", "Type1": "Poison", "Type2": "", "HP": 40, "Attack": 65, "Defense": 95, "Speed": 35, "Special": 60},
    {"Number": 110, "Name": "Weezing", "Type1": "Poison", "Type2": "", "HP": 65, "Attack": 90, "Defense": 120, "Speed": 60, "Special": 85},
    {"Number": 111, "Name": "Rhyhorn", "Type1": "Ground", "Type2": "Rock", "HP": 80, "Attack": 85, "Defense": 95, "Speed": 25, "Special": 30},
    {"Number": 112, "Name": "Rhydon", "Type1": "Ground", "Type2": "Rock", "HP": 105, "Attack": 130, "Defense": 120, "Speed": 40, "Special": 45},
    {"Number": 113, "Name": "Chansey", "Type1": "Normal", "Type2": "", "HP": 250, "Attack": 5, "Defense": 5, "Speed": 50, "Special": 105},
    {"Number": 114, "Name": "Tangela", "Type1": "Grass", "Type2": "", "HP": 65, "Attack": 55, "Defense": 115, "Speed": 60, "Special": 100},
    {"Number": 115, "Name": "Kangaskhan", "Type1": "Normal", "Type2": "", "HP": 105, "Attack": 95, "Defense": 80, "Speed": 90, "Special": 40},
    {"Number": 116, "Name": "Horsea", "Type1": "Water", "Type2": "", "HP": 30, "Attack": 40, "Defense": 70, "Speed": 60, "Special": 70},
    {"Number": 117, "Name": "Seadra", "Type1": "Water", "Type2": "", "HP": 55, "Attack": 65, "Defense": 95, "Speed": 85, "Special": 95},
    {"Number": 118, "Name": "Goldeen", "Type1": "Water", "Type2": "", "HP": 45, "Attack": 67, "Defense": 60, "Speed": 63, "Special": 50},
    {"Number": 119, "Name": "Seaking", "Type1": "Water", "Type2": "", "HP": 80, "Attack": 92, "Defense": 65, "Speed": 68, "Special": 80},
    {"Number": 120, "Name": "Staryu", "Type1": "Water", "Type2": "", "HP": 30, "Attack": 45, "Defense": 55, "Speed": 85, "Special": 70},
    {"Number": 121, "Name": "Starmie", "Type1": "Water", "Type2": "Psychic", "HP": 60, "Attack": 75, "Defense": 85, "Speed": 115, "Special": 100},
    {"Number": 122, "Name": "Mr.Mime", "Type1": "Psychic", "Type2": "", "HP": 40, "Attack": 45, "Defense": 65, "Speed": 90, "Special": 100},
    {"Number": 123, "Name": "Scyther", "Type1": "Bug", "Type2": "Flying", "HP": 70, "Attack": 110, "Defense": 80, "Speed": 105, "Special": 55},
    {"Number": 124, "Name": "Jynx", "Type1": "Ice", "Type2": "Psychic", "HP": 65, "Attack": 50, "Defense": 35, "Speed": 95, "Special": 95},
    {"Number": 125, "Name": "Electabuzz", "Type1": "Electric", "Type2": "", "HP": 65, "Attack": 83, "Defense": 57, "Speed": 105, "Special": 85},
    {"Number": 126, "Name": "Magmar", "Type1": "Fire", "Type2": "", "HP": 65, "Attack": 95, "Defense": 57, "Speed": 93, "Special": 85},
    {"Number": 127, "Name": "Pinsir", "Type1": "Bug", "Type2": "", "HP": 65, "Attack": 125, "Defense": 100, "Speed": 85, "Special": 55},
    {"Number": 128, "Name": "Tauros", "Type1": "Normal", "Type2": "", "HP": 75, "Attack": 100, "Defense": 95, "Speed": 110, "Special": 70},
    {"Number": 129, "Name": "Magikarp", "Type1": "Water", "Type2": "", "HP": 20, "Attack": 10, "Defense": 55, "Speed": 80, "Special": 20},
    {"Number": 130, "Name": "Gyarados", "Type1": "Water", "Type2": "Flying", "HP": 95, "Attack": 125, "Defense": 79, "Speed": 81, "Special": 100},
    {"Number": 131, "Name": "Lapras", "Type1": "Water", "Type2": "Ice", "HP": 130, "Attack": 85, "Defense": 80, "Speed": 60, "Special": 95},
    {"Number": 132, "Name": "Ditto", "Type1": "Normal", "Type2": "", "HP": 48, "Attack": 48, "Defense": 48, "Speed": 48, "Special": 48},
    {"Number": 133, "Name": "Eevee", "Type1": "Normal", "Type2": "", "HP": 55, "Attack": 55, "Defense": 50, "Speed": 55, "Special": 65},
    {"Number": 134, "Name": "Vaporeon", "Type1": "Water", "Type2": "", "HP": 130, "Attack": 65, "Defense": 60, "Speed": 65, "Special": 110},
    {"Number": 135, "Name": "Jolteon", "Type1": "Electric", "Type2": "", "HP": 65, "Attack": 65, "Defense": 60, "Speed": 130, "Special": 110},
    {"Number": 136, "Name": "Flareon", "Type1": "Fire", "Type2": "", "HP": 65, "Attack": 130, "Defense": 60, "Speed": 65, "Special": 110},
    {"Number": 137, "Name": "Porygon", "Type1": "Normal", "Type2": "", "HP": 65, "Attack": 60, "Defense": 70, "Speed": 40, "Special": 75},
    {"Number": 138, "Name": "Omanyte", "Type1": "Rock", "Type2": "Water", "HP": 35, "Attack": 40, "Defense": 100, "Speed": 35, "Special": 90},
    {"Number": 139, "Name": "Omastar", "Type1": "Rock", "Type2": "Water", "HP": 70, "Attack": 60, "Defense": 125, "Speed": 55, "Special": 115},
    {"Number": 140, "Name": "Kabuto", "Type1": "Rock", "Type2": "Water", "HP": 30, "Attack": 80, "Defense": 90, "Speed": 55, "Special": 45},
    {"Number": 141, "Name": "Kabutops", "Type1": "Rock", "Type2": "Water", "HP": 60, "Attack": 115, "Defense": 105, "Speed": 80, "Special": 70},
    {"Number": 142, "Name": "Aerodactyl", "Type1": "Rock", "Type2": "Flying", "HP": 80, "Attack": 105, "Defense": 65, "Speed": 130, "Special": 60},
    {"Number": 143, "Name": "Snorlax", "Type1": "Normal", "Type2": "", "HP": 160, "Attack": 110, "Defense": 65, "Speed": 30, "Special": 65},
    {"Number": 144, "Name": "Articuno", "Type1": "Ice", "Type2": "Flying", "HP": 90, "Attack": 85, "Defense": 100, "Speed": 85, "Special": 125},
    {"Number": 145, "Name": "Zapdos", "Type1": "Electric", "Type2": "Flying", "HP": 90, "Attack": 90, "Defense": 85, "Speed": 100, "Special": 125},
    {"Number": 146, "Name": "Moltres", "Type1": "Fire", "Type2": "Flying", "HP": 90, "Attack": 100, "Defense": 90, "Speed": 90, "Special": 125},
    {"Number": 147, "Name": "Dratini", "Type1": "Dragon", "Type2": "", "HP": 41, "Attack": 64, "Defense": 45, "Speed": 50, "Special": 50},
    {"Number": 148, "Name": "Dragonair", "Type1": "Dragon", "Type2": "", "HP": 61, "Attack": 84, "Defense": 65, "Speed": 70, "Special": 70},
    {"Number": 149, "Name": "Dragonite", "Type1": "Dragon", "Type2": "Flying", "HP": 91, "Attack": 134, "Defense": 95, "Speed": 80, "Special": 100},
    {"Number": 150, "Name": "Mewtwo", "Type1": "Psychic", "Type2": "", "HP": 106, "Attack": 110, "Defense": 90, "Speed": 130, "Special": 154},
    {"Number": 151, "Name": "Mew", "Type1": "Psychic", "Type2": "", "HP": 100, "Attack": 100, "Defense": 100, "Speed": 100, "Special": 100}
]

type_multiplicator = {
    "Normal": {"Normal": 1, "Fire": 1, "Water": 1, "Electric": 1, "Grass": 1, "Ice": 1, "Fighting": 1, "Poison": 1, "Ground": 1, "Flying": 1,
               "Psychic": 1, "Bug": 1, "Rock": 0.5, "Ghost": 0, "Dragon": 1, "": 1},
    "Fire": {"Normal": 1, "Fire": 0.5, "Water": 0.5, "Electric": 1, "Grass": 2, "Ice": 2, "Fighting": 1, "Poison": 1, "Ground": 1, "Flying": 1,
             "Psychic": 1, "Bug": 2, "Rock": 0.5, "Ghost": 1, "Dragon": 0.5, "": 1},
    "Water": {"Normal": 1, "Fire": 2, "Water": 0.5, "Electric": 1, "Grass": 0.5, "Ice": 1, "Fighting": 1, "Poison": 1, "Ground": 2, "Flying": 1,
              "Psychic": 1, "Bug": 1, "Rock": 2, "Ghost": 1, "Dragon": 0.5, "": 1},
    "Electric": {"Normal": 1, "Fire": 1, "Water": 2, "Electric": 0.5, "Grass": 0.5, "Ice": 1, "Fighting": 1, "Poison": 1, "Ground": 0, "Flying": 2,
                 "Psychic": 1, "Bug": 1, "Rock": 1, "Ghost": 1, "Dragon": 0.5, "": 1},
    "Grass": {"Normal": 1, "Fire": 0.5, "Water": 2, "Electric": 1, "Grass": 0.5, "Ice": 1, "Fighting": 1, "Poison": 0.5, "Ground": 2, "Flying": 0.5,
              "Psychic": 1, "Bug": 0.5, "Rock": 2, "Ghost": 1, "Dragon": 0.5, "": 1},
    "Ice": {"Normal": 1, "Fire": 0.5, "Water": 0.5, "Electric": 1, "Grass": 2, "Ice": 0.5, "Fighting": 1, "Poison": 1, "Ground": 2, "Flying": 2,
            "Psychic": 1, "Bug": 1, "Rock": 1, "Ghost": 1, "Dragon": 2, "": 1},
    "Fighting": {"Normal": 2, "Fire": 1, "Water": 1, "Electric": 1, "Grass": 1, "Ice": 2, "Fighting": 1, "Poison": 0.5, "Ground": 1, "Flying": 0.5,
                 "Psychic": 0.5, "Bug": 0.5, "Rock": 2, "Ghost": 0, "Dragon": 1, "": 1},
    "Poison": {"Normal": 1, "Fire": 1, "Water": 1, "Electric": 1, "Grass": 2, "Ice": 1, "Fighting": 1, "Poison": 0.5, "Ground": 0.5, "Flying": 1,
               "Psychic": 1, "Bug": 1, "Rock": 0.5, "Ghost": 0.5, "Dragon": 1, "": 1},
    "Ground": {"Normal": 1, "Fire": 2, "Water": 1, "Electric": 2, "Grass": 0.5, "Ice": 1, "Fighting": 1, "Poison": 2, "Ground": 1, "Flying": 0,
               "Psychic": 1, "Bug": 0.5, "Rock": 2, "Ghost": 1, "Dragon": 1, "": 1},
    "Flying": {"Normal": 1, "Fire": 1, "Water": 1, "Electric": 0.5, "Grass": 2, "Ice": 1, "Fighting": 2, "Poison": 1, "Ground": 1, "Flying": 1,
               "Psychic": 1, "Bug": 2, "Rock": 0.5, "Ghost": 1, "Dragon": 1, "": 1},
    "Psychic": {"Normal": 1, "Fire": 1, "Water": 1, "Electric": 1, "Grass": 1, "Ice": 1, "Fighting": 2, "Poison": 2, "Ground": 1, "Flying": 1,
                "Psychic": 0.5, "Bug": 1, "Rock": 1, "Ghost": 1, "Dragon": 1, "": 1},
    "Bug": {"Normal": 1, "Fire": 0.5, "Water": 1, "Electric": 1, "Grass": 2, "Ice": 1, "Fighting": 0.5, "Poison": 0.5, "Ground": 1, "Flying": 0.5,
            "Psychic": 2, "Bug": 1, "Rock": 1, "Ghost": 0.5, "Dragon": 1, "": 1},
    "Rock": {"Normal": 1, "Fire": 2, "Water": 1, "Electric": 1, "Grass": 1, "Ice": 2, "Fighting": 0.5, "Poison": 1, "Ground": 0.5, "Flying": 2,
             "Psychic": 1, "Bug": 2, "Rock": 1, "Ghost": 1, "Dragon": 1, "": 1},
    "Ghost": {"Normal": 0, "Fire": 1, "Water": 1, "Electric": 1, "Grass": 1, "Ice": 1, "Fighting": 1, "Poison": 1, "Ground": 1, "Flying": 1,
              "Psychic": 0, "Bug": 1, "Rock": 1, "Ghost": 2, "Dragon": 1, "": 1},
    "Dragon": {"Normal": 1, "Fire": 1, "Water": 1, "Electric": 1, "Grass": 1, "Ice": 1, "Fighting": 1, "Poison": 1, "Ground": 1, "Flying": 1,
               "Psychic": 1, "Bug": 1, "Rock": 1, "Ghost": 1, "Dragon": 2, "": 1}
}

move = [
    {"Name": "Absorb", "Type": "Grass", "Cat.": "Special", "Power": 20, "Acc.": 100, "PP": 25,
     "Effect": "User recovers half the HP inflicted on opponent."},
    {"Name": "Acid", "Type": "Poison", "Cat.": "Special", "Power": 40, "Acc.": 100, "PP": 30, "Effect": "May lower opponent's Special Defense."},
    {"Name": "Acid Armor", "Type": "Poison", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 20, "Effect": "Sharply raises user's Defense."},
    {"Name": "Agility", "Type": "Psychic", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 30, "Effect": "Sharply raises user's Speed."},
    {"Name": "Amnesia", "Type": "Psychic", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 20, "Effect": "Sharply raises user's Special Defense."},
    {"Name": "Aurora Beam", "Type": "Ice", "Cat.": "Special", "Power": 65, "Acc.": 100, "PP": 20, "Effect": "May lower opponent's Attack."},
    {"Name": "Barrage", "Type": "Normal", "Cat.": "Physical", "Power": 15, "Acc.": 85, "PP": 20, "Effect": "Hits 2-5 times in one turn."},
    {"Name": "Barrier", "Type": "Psychic", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 20, "Effect": "Sharply raises user's Defense."},
    {"Name": "Bide", "Type": "Normal", "Cat.": "Physical", "Power": 0, "Acc.": 100, "PP": 10,
     "Effect": "User takes damage for two turns then strikes back double."},
    {"Name": "Bind", "Type": "Normal", "Cat.": "Physical", "Power": 15, "Acc.": 85, "PP": 20,
     "Effect": "Traps opponent, damaging them for 4-5 turns."},
    {"Name": "Bite", "Type": "Normal", "Cat.": "Physical", "Power": 60, "Acc.": 100, "PP": 25, "Effect": "May cause flinching."},
    {"Name": "Blizzard", "Type": "Ice", "Cat.": "Special", "Power": 110, "Acc.": 70, "PP": 5, "Effect": "May freeze opponent."},
    {"Name": "Body Slam", "Type": "Normal", "Cat.": "Physical", "Power": 85, "Acc.": 100, "PP": 15, "Effect": "May paralyze opponent."},
    {"Name": "Bone Club", "Type": "Ground", "Cat.": "Physical", "Power": 65, "Acc.": 85, "PP": 20, "Effect": "May cause flinching."},
    {"Name": "Bonemerang", "Type": "Ground", "Cat.": "Physical", "Power": 50, "Acc.": 90, "PP": 10, "Effect": "Hits twIce in one turn."},
    {"Name": "Bubble", "Type": "Water", "Cat.": "Special", "Power": 40, "Acc.": 100, "PP": 30, "Effect": "May lower opponent's Speed."},
    {"Name": "Bubble Beam", "Type": "Water", "Cat.": "Special", "Power": 65, "Acc.": 100, "PP": 20, "Effect": "May lower opponent's Speed."},
    {"Name": "Clamp", "Type": "Water", "Cat.": "Physical", "Power": 35, "Acc.": 85, "PP": 10,
     "Effect": "Traps opponent, damaging them for 4-5 turns."},
    {"Name": "Comet Punch", "Type": "Normal", "Cat.": "Physical", "Power": 18, "Acc.": 85, "PP": 15, "Effect": "Hits 2-5 times in one turn."},
    {"Name": "Confuse Ray", "Type": "Ghost", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 10, "Effect": "Confuses opponent."},
    {"Name": "Confusion", "Type": "Psychic", "Cat.": "Special", "Power": 50, "Acc.": 100, "PP": 25, "Effect": "May confuse opponent."},
    {"Name": "Constrict", "Type": "Normal", "Cat.": "Physical", "Power": 10, "Acc.": 100, "PP": 35,
     "Effect": "May lower opponent's Speed by one stage."},
    {"Name": "Conversion", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 30,
     "Effect": "Changes user's type to that of its first move."},
    {"Name": "Counter", "Type": "Fighting", "Cat.": "Physical", "Power": 0, "Acc.": 100, "PP": 20,
     "Effect": "When hit by a Physical Attack, user strikes back with 2x power."},
    {"Name": "Crabhammer", "Type": "Water", "Cat.": "Physical", "Power": 100, "Acc.": 90, "PP": 10, "Effect": "High critical hit ratio."},
    {"Name": "Cut", "Type": "Normal", "Cat.": "Physical", "Power": 50, "Acc.": 95, "PP": 30, "Effect": ""},
    {"Name": "Defense Curl", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 40, "Effect": "Raises user's Defense."},
    {"Name": "Dig", "Type": "Ground", "Cat.": "Physical", "Power": 80, "Acc.": 100, "PP": 10,
     "Effect": "Digs underGround on first turn, attacks on second. Can also escape from caves."},
    {"Name": "Disable", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 20,
     "Effect": "Opponent can't use its last attack for a few turns."},
    {"Name": "Dizzy Punch", "Type": "Normal", "Cat.": "Physical", "Power": 70, "Acc.": 100, "PP": 10, "Effect": "May confuse opponent."},
    {"Name": "Double Kick", "Type": "Fighting", "Cat.": "Physical", "Power": 30, "Acc.": 100, "PP": 30, "Effect": "Hits twIce in one turn."},
    {"Name": "Double Slap", "Type": "Normal", "Cat.": "Physical", "Power": 15, "Acc.": 85, "PP": 10, "Effect": "Hits 2-5 times in one turn."},
    {"Name": "Double Team", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 15, "Effect": "Raises user's Evasiveness."},
    {"Name": "Double-Edge", "Type": "Normal", "Cat.": "Physical", "Power": 120, "Acc.": 100, "PP": 15, "Effect": "User receives recoil damage."},
    {"Name": "Dragon Rage", "Type": "Dragon", "Cat.": "Special", "Power": 0, "Acc.": 100, "PP": 10, "Effect": "Always inflicts 40 HP."},
    {"Name": "Dream Eater", "Type": "Psychic", "Cat.": "Special", "Power": 100, "Acc.": 100, "PP": 15,
     "Effect": "User recovers half the HP inflicted on a sleeping opponent."},
    {"Name": "Drill Peck", "Type": "Flying", "Cat.": "Physical", "Power": 80, "Acc.": 100, "PP": 20, "Effect": ""},
    {"Name": "Earthquake", "Type": "Ground", "Cat.": "Physical", "Power": 100, "Acc.": 100, "PP": 10,
     "Effect": "Power is doubled if opponent is underGround from using Dig."},
    {"Name": "Egg Bomb", "Type": "Normal", "Cat.": "Physical", "Power": 100, "Acc.": 75, "PP": 10, "Effect": ""},
    {"Name": "Ember", "Type": "Fire", "Cat.": "Special", "Power": 40, "Acc.": 100, "PP": 25, "Effect": "May burn opponent."},
    {"Name": "Explosion", "Type": "Normal", "Cat.": "Physical", "Power": 250, "Acc.": 100, "PP": 5, "Effect": "User faints."},
    {"Name": "Fire Blast", "Type": "Fire", "Cat.": "Special", "Power": 110, "Acc.": 85, "PP": 5, "Effect": "May burn opponent."},
    {"Name": "Fire Punch", "Type": "Fire", "Cat.": "Physical", "Power": 75, "Acc.": 100, "PP": 15, "Effect": "May burn opponent."},
    {"Name": "Fire Spin", "Type": "Fire", "Cat.": "Special", "Power": 35, "Acc.": 85, "PP": 15,
     "Effect": "Traps opponent, damaging them for 4-5 turns."},
    {"Name": "Fissure", "Type": "Ground", "Cat.": "Physical", "Power": 0, "Acc.": 100, "PP": 5, "Effect": "One-Hit-KO, if it hits."},
    {"Name": "Flamethrower", "Type": "Fire", "Cat.": "Special", "Power": 90, "Acc.": 100, "PP": 15, "Effect": "May burn opponent."},
    {"Name": "Flash", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 20, "Effect": "Lowers opponent's Accuracy."},
    {"Name": "Fly", "Type": "Flying", "Cat.": "Physical", "Power": 90, "Acc.": 95, "PP": 15,
     "Effect": "Flies up on first turn, attacks on second turn."},
    {"Name": "Focus Energy", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 30, "Effect": "Increases critical hit ratio."},
    {"Name": "Fury Attack", "Type": "Normal", "Cat.": "Physical", "Power": 15, "Acc.": 85, "PP": 20, "Effect": "Hits 2-5 times in one turn."},
    {"Name": "Fury Swipes", "Type": "Normal", "Cat.": "Physical", "Power": 18, "Acc.": 80, "PP": 15, "Effect": "Hits 2-5 times in one turn."},
    {"Name": "Glare", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 30, "Effect": "Paralyzes opponent."},
    {"Name": "Growl", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 40, "Effect": "Lowers opponent's Attack."},
    {"Name": "Growth", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 40, "Effect": "Raises user's Attack and Special Attack."},
    {"Name": "Guillotine", "Type": "Normal", "Cat.": "Physical", "Power": 0, "Acc.": 100, "PP": 5, "Effect": "One-Hit-KO, if it hits."},
    {"Name": "Gust", "Type": "Flying", "Cat.": "Special", "Power": 40, "Acc.": 100, "PP": 35,
     "Effect": "Hits Pokemon using Fly/Bounce with double power."},
    {"Name": "Harden", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 30, "Effect": "Raises user's Defense."},
    {"Name": "Haze", "Type": "Ice", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 30, "Effect": "Resets all stat changes."},
    {"Name": "Headbutt", "Type": "Normal", "Cat.": "Physical", "Power": 70, "Acc.": 100, "PP": 15, "Effect": "May cause flinching."},
    {"Name": "High Jump Kick", "Type": "Fighting", "Cat.": "Physical", "Power": 130, "Acc.": 90, "PP": 10,
     "Effect": "If it misses, the user loses half their HP."},
    {"Name": "Horn Attack", "Type": "Normal", "Cat.": "Physical", "Power": 65, "Acc.": 100, "PP": 25, "Effect": ""},
    {"Name": "Horn Drill", "Type": "Normal", "Cat.": "Physical", "Power": 0, "Acc.": 100, "PP": 5, "Effect": "One-Hit-KO, if it hits."},
    {"Name": "Hydro Pump", "Type": "Water", "Cat.": "Special", "Power": 110, "Acc.": 80, "PP": 5, "Effect": ""},
    {"Name": "Hyper Beam", "Type": "Normal", "Cat.": "Special", "Power": 150, "Acc.": 90, "PP": 5, "Effect": "User must recharge next turn."},
    {"Name": "Hyper Fang", "Type": "Normal", "Cat.": "Physical", "Power": 80, "Acc.": 90, "PP": 15, "Effect": "May cause flinching."},
    {"Name": "Hypnosis", "Type": "Psychic", "Cat.": "Status", "Power": 0, "Acc.": 60, "PP": 20, "Effect": "Puts opponent to sleep."},
    {"Name": "Ice Beam", "Type": "Ice", "Cat.": "Special", "Power": 90, "Acc.": 100, "PP": 10, "Effect": "May freeze opponent."},
    {"Name": "Ice Punch", "Type": "Ice", "Cat.": "Physical", "Power": 75, "Acc.": 100, "PP": 15, "Effect": "May freeze opponent."},
    {"Name": "Jump Kick", "Type": "Fighting", "Cat.": "Physical", "Power": 100, "Acc.": 95, "PP": 10,
     "Effect": "If it misses, the user loses half their HP."},
    {"Name": "Karate Chop", "Type": "Fighting", "Cat.": "Physical", "Power": 50, "Acc.": 100, "PP": 25, "Effect": "High critical hit ratio."},
    {"Name": "Kinesis", "Type": "Psychic", "Cat.": "Status", "Power": 0, "Acc.": 80, "PP": 15, "Effect": "Lowers opponent's Accuracy."},
    {"Name": "Leech Life", "Type": "Bug", "Cat.": "Physical", "Power": 80, "Acc.": 100, "PP": 10,
     "Effect": "User recovers half the HP inflicted on opponent."},
    {"Name": "Leech Seed", "Type": "Grass", "Cat.": "Status", "Power": 0, "Acc.": 90, "PP": 10, "Effect": "User steals HP from opponent each turn."},
    {"Name": "Leer", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 30, "Effect": "Lowers opponent's Defense."},
    {"Name": "Lick", "Type": "Ghost", "Cat.": "Physical", "Power": 30, "Acc.": 100, "PP": 30, "Effect": "May paralyze opponent."},
    {"Name": "Light Screen", "Type": "Psychic", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 30,
     "Effect": "Halves damage from Special attacks for 5 turns."},
    {"Name": "Lovely Kiss", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 75, "PP": 10, "Effect": "Puts opponent to sleep."},
    {"Name": "Low Kick", "Type": "Fighting", "Cat.": "Physical", "Power": 0, "Acc.": 100, "PP": 20,
     "Effect": "The heavier the opponent, the stronger the attack."},
    {"Name": "Meditate", "Type": "Psychic", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 40, "Effect": "Raises user's Attack."},
    {"Name": "Mega Drain", "Type": "Grass", "Cat.": "Special", "Power": 40, "Acc.": 100, "PP": 15,
     "Effect": "User recovers half the HP inflicted on opponent."},
    {"Name": "Mega Kick", "Type": "Normal", "Cat.": "Physical", "Power": 120, "Acc.": 75, "PP": 5, "Effect": ""},
    {"Name": "Mega Punch", "Type": "Normal", "Cat.": "Physical", "Power": 80, "Acc.": 85, "PP": 20, "Effect": ""},
    {"Name": "Metronome", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 10,
     "Effect": "User performs any move in the game at random."},
    {"Name": "Mimic", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 10, "Effect": "Copies the opponent's last move."},
    {"Name": "Minimize", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 10, "Effect": "Sharply raises user's Evasiveness."},
    {"Name": "Mirror Move", "Type": "Flying", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 20,
     "Effect": "User performs the opponent's last move."},
    {"Name": "Mist", "Type": "Ice", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 30,
     "Effect": "User's stats cannot be changed for a period of time."},
    {"Name": "Night Shade", "Type": "Ghost", "Cat.": "Special", "Power": 0, "Acc.": 100, "PP": 15,
     "Effect": "Inflicts damage equal to user's level."},
    {"Name": "Pay Day", "Type": "Normal", "Cat.": "Physical", "Power": 40, "Acc.": 100, "PP": 20,
     "Effect": "A small amount of money is gained after the battle resolves."},
    {"Name": "Peck", "Type": "Flying", "Cat.": "Physical", "Power": 35, "Acc.": 100, "PP": 35, "Effect": ""},
    {"Name": "Petal Dance", "Type": "Grass", "Cat.": "Special", "Power": 120, "Acc.": 100, "PP": 10,
     "Effect": "User attacks for 2-3 turns but then becomes confused."},
    {"Name": "Pin Missile", "Type": "Bug", "Cat.": "Physical", "Power": 25, "Acc.": 95, "PP": 20, "Effect": "Hits 2-5 times in one turn."},
    {"Name": "Poison Gas", "Type": "Poison", "Cat.": "Status", "Power": 0, "Acc.": 90, "PP": 40, "Effect": "Poisons opponent."},
    {"Name": "Poison Powder", "Type": "Poison", "Cat.": "Status", "Power": 0, "Acc.": 75, "PP": 35, "Effect": "Poisons opponent."},
    {"Name": "Poison Sting", "Type": "Poison", "Cat.": "Physical", "Power": 15, "Acc.": 100, "PP": 35, "Effect": "May Poison the opponent."},
    {"Name": "Pound", "Type": "Normal", "Cat.": "Physical", "Power": 40, "Acc.": 100, "PP": 35, "Effect": ""},
    {"Name": "Psybeam", "Type": "Psychic", "Cat.": "Special", "Power": 65, "Acc.": 100, "PP": 20, "Effect": "May confuse opponent."},
    {"Name": "Psychic", "Type": "Psychic", "Cat.": "Special", "Power": 90, "Acc.": 100, "PP": 10, "Effect": "May lower opponent's Special Defense."},
    {"Name": "Psywave", "Type": "Psychic", "Cat.": "Special", "Power": 0, "Acc.": 80, "PP": 15, "Effect": "Inflicts damage 50-150% of user's level."},
    {"Name": "Quick Attack", "Type": "Normal", "Cat.": "Physical", "Power": 40, "Acc.": 100, "PP": 30, "Effect": "User attacks first."},
    {"Name": "Rage", "Type": "Normal", "Cat.": "Physical", "Power": 20, "Acc.": 100, "PP": 20, "Effect": "Raises user's Attack when hit."},
    {"Name": "Razor Leaf", "Type": "Grass", "Cat.": "Physical", "Power": 55, "Acc.": 95, "PP": 25, "Effect": "High critical hit ratio."},
    {"Name": "Razor Wind", "Type": "Normal", "Cat.": "Special", "Power": 80, "Acc.": 100, "PP": 10,
     "Effect": "Charges on first turn, attacks on second. High critical hit ratio."},
    {"Name": "Recover", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 10, "Effect": "User recovers half its max HP."},
    {"Name": "Reflect", "Type": "Psychic", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 20,
     "Effect": "Halves damage from Physical attacks for 5 turns."},
    {"Name": "Rest", "Type": "Psychic", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 10,
     "Effect": "User sleeps for 2 turns, but user is fully healed."},
    {"Name": "Roar", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 20,
     "Effect": "In battles, the opponent switches. In the wild, the Pokemon runs."},
    {"Name": "Rock Slide", "Type": "ROCK", "Cat.": "Physical", "Power": 75, "Acc.": 90, "PP": 10, "Effect": "May cause flinching."},
    {"Name": "Rock Throw", "Type": "ROCK", "Cat.": "Physical", "Power": 50, "Acc.": 90, "PP": 15, "Effect": ""},
    {"Name": "Rolling Kick", "Type": "Fighting", "Cat.": "Physical", "Power": 60, "Acc.": 85, "PP": 15, "Effect": "May cause flinching."},
    {"Name": "Sand Attack", "Type": "Ground", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 15, "Effect": "Lowers opponent's Accuracy."},
    {"Name": "Scratch", "Type": "Normal", "Cat.": "Physical", "Power": 40, "Acc.": 100, "PP": 35, "Effect": ""},
    {"Name": "Screech", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 85, "PP": 40, "Effect": "Sharply lowers opponent's Defense."},
    {"Name": "Seismic Toss", "Type": "Fighting", "Cat.": "Physical", "Power": 0, "Acc.": 100, "PP": 20,
     "Effect": "Inflicts damage equal to user's level."},
    {"Name": "Self-Destruct", "Type": "Normal", "Cat.": "Physical", "Power": 200, "Acc.": 100, "PP": 5, "Effect": "User faints."},
    {"Name": "Sharpen", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 30, "Effect": "Raises user's Attack."},
    {"Name": "Sing", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 55, "PP": 15, "Effect": "Puts opponent to sleep."},
    {"Name": "Skull Bash", "Type": "Normal", "Cat.": "Physical", "Power": 130, "Acc.": 100, "PP": 10,
     "Effect": "Raises Defense on first turn, attacks on second."},
    {"Name": "Sky Attack", "Type": "Flying", "Cat.": "Physical", "Power": 140, "Acc.": 90, "PP": 5,
     "Effect": "Charges on first turn, attacks on second. May cause flinching."},
    {"Name": "Slam", "Type": "Normal", "Cat.": "Physical", "Power": 80, "Acc.": 75, "PP": 20, "Effect": ""},
    {"Name": "Slash", "Type": "Normal", "Cat.": "Physical", "Power": 70, "Acc.": 100, "PP": 20, "Effect": "High critical hit ratio."},
    {"Name": "Sleep Powder", "Type": "Grass", "Cat.": "Status", "Power": 0, "Acc.": 75, "PP": 15, "Effect": "Puts opponent to sleep."},
    {"Name": "Sludge", "Type": "Poison", "Cat.": "Special", "Power": 65, "Acc.": 100, "PP": 20, "Effect": "May Poison opponent."},
    {"Name": "Smog", "Type": "Poison", "Cat.": "Special", "Power": 30, "Acc.": 70, "PP": 20, "Effect": "May Poison opponent."},
    {"Name": "Smokescreen", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 20, "Effect": "Lowers opponent's Accuracy."},
    {"Name": "Soft-Boiled", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 10, "Effect": "User recovers half its max HP."},
    {"Name": "Solar Beam", "Type": "Grass", "Cat.": "Special", "Power": 120, "Acc.": 100, "PP": 10,
     "Effect": "Charges on first turn, attacks on second."},
    {"Name": "Sonic Boom", "Type": "Normal", "Cat.": "Special", "Power": 0, "Acc.": 90, "PP": 20, "Effect": "Always inflicts 20 HP."},
    {"Name": "Spike Cannon", "Type": "Normal", "Cat.": "Physical", "Power": 20, "Acc.": 100, "PP": 15, "Effect": "Hits 2-5 times in one turn."},
    {"Name": "Splash", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 40, "Effect": "Doesn't do ANYTHING."},
    {"Name": "Spore", "Type": "Grass", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 15, "Effect": "Puts opponent to sleep."},
    {"Name": "Stomp", "Type": "Normal", "Cat.": "Physical", "Power": 65, "Acc.": 100, "PP": 20, "Effect": "May cause flinching."},
    {"Name": "Strength", "Type": "Normal", "Cat.": "Physical", "Power": 80, "Acc.": 100, "PP": 15, "Effect": ""},
    {"Name": "String Shot", "Type": "Bug", "Cat.": "Status", "Power": 0, "Acc.": 95, "PP": 40, "Effect": "Sharply lowers opponent's Speed."},
    {"Name": "Struggle", "Type": "Normal", "Cat.": "Physical", "Power": 50, "Acc.": 100, "PP": 100,
     "Effect": "Only usable when all PP are gone. Hurts the user."},
    {"Name": "Stun Spore", "Type": "Grass", "Cat.": "Status", "Power": 0, "Acc.": 75, "PP": 30, "Effect": "Paralyzes opponent."},
    {"Name": "Submission", "Type": "Fighting", "Cat.": "Physical", "Power": 80, "Acc.": 80, "PP": 20, "Effect": "User receives recoil damage."},
    {"Name": "Substitute", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 10,
     "Effect": "Uses HP to creates a decoy that takes hits."},
    {"Name": "Super Fang", "Type": "Normal", "Cat.": "Physical", "Power": 0, "Acc.": 90, "PP": 10,
     "Effect": "Always takes off half of the opponent's HP."},
    {"Name": "Supersonic", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 55, "PP": 20, "Effect": "Confuses opponent."},
    {"Name": "Surf", "Type": "Water", "Cat.": "Special", "Power": 90, "Acc.": 100, "PP": 15, "Effect": "Hits all adjacent Pokemon."},
    {"Name": "Swift", "Type": "Normal", "Cat.": "Special", "Power": 60, "Acc.": 100, "PP": 20, "Effect": "Ignores Accuracy and Evasiveness."},
    {"Name": "Swords Dance", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 20, "Effect": "Sharply raises user's Attack."},
    {"Name": "Tackle", "Type": "Normal", "Cat.": "Physical", "Power": 40, "Acc.": 100, "PP": 35, "Effect": ""},
    {"Name": "Tail Whip", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 30, "Effect": "Lowers opponent's Defense."},
    {"Name": "Take Down", "Type": "Normal", "Cat.": "Physical", "Power": 90, "Acc.": 85, "PP": 20, "Effect": "User receives recoil damage."},
    {"Name": "Teleport", "Type": "Psychic", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 20,
     "Effect": "Allows user to flee wild battles; also warps player to last PokeCenter."},
    {"Name": "Thrash", "Type": "Normal", "Cat.": "Physical", "Power": 120, "Acc.": 100, "PP": 10,
     "Effect": "User attacks for 2-3 turns but then becomes confused."},
    {"Name": "Thunder", "Type": "Electric", "Cat.": "Special", "Power": 110, "Acc.": 70, "PP": 10, "Effect": "May paralyze opponent."},
    {"Name": "Thunder Punch", "Type": "Electric", "Cat.": "Physical", "Power": 75, "Acc.": 100, "PP": 15, "Effect": "May paralyze opponent."},
    {"Name": "Thunder Shock", "Type": "Electric", "Cat.": "Special", "Power": 40, "Acc.": 100, "PP": 30, "Effect": "May paralyze opponent."},
    {"Name": "Thunder Wave", "Type": "Electric", "Cat.": "Status", "Power": 0, "Acc.": 90, "PP": 20, "Effect": "Paralyzes opponent."},
    {"Name": "Thunderbolt", "Type": "Electric", "Cat.": "Special", "Power": 90, "Acc.": 100, "PP": 15, "Effect": "May paralyze opponent."},
    {"Name": "Toxic", "Type": "Poison", "Cat.": "Status", "Power": 0, "Acc.": 90, "PP": 10, "Effect": "Badly Poisons opponent."},
    {"Name": "Transform", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 10,
     "Effect": "User takes on the form and attacks of the opponent."},
    {"Name": "Tri Attack", "Type": "Normal", "Cat.": "Special", "Power": 80, "Acc.": 100, "PP": 10,
     "Effect": "May paralyze, burn or freeze opponent."},
    {"Name": "Twineedle", "Type": "Bug", "Cat.": "Physical", "Power": 25, "Acc.": 100, "PP": 20,
     "Effect": "Hits twIce in one turn. May Poison opponent."},
    {"Name": "VIce Grip", "Type": "Normal", "Cat.": "Physical", "Power": 55, "Acc.": 100, "PP": 30, "Effect": ""},
    {"Name": "Vine Whip", "Type": "Grass", "Cat.": "Physical", "Power": 45, "Acc.": 100, "PP": 25, "Effect": ""},
    {"Name": "Water Gun", "Type": "Water", "Cat.": "Special", "Power": 40, "Acc.": 100, "PP": 25, "Effect": ""},
    {"Name": "Waterfall", "Type": "Water", "Cat.": "Physical", "Power": 80, "Acc.": 100, "PP": 15, "Effect": "May cause flinching."},
    {"Name": "Whirlwind", "Type": "Normal", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 20,
     "Effect": "In battles, the opponent switches. In the wild, the Pokemon runs."},
    {"Name": "Wing Attack", "Type": "Flying", "Cat.": "Physical", "Power": 60, "Acc.": 100, "PP": 35, "Effect": ""},
    {"Name": "Withdraw", "Type": "Water", "Cat.": "Status", "Power": 0, "Acc.": 100, "PP": 40, "Effect": "Raises user's Defense."},
    {"Name": "Wrap", "Type": "Normal", "Cat.": "Physical", "Power": 15, "Acc.": 90, "PP": 20,
     "Effect": "Traps opponent, damaging them for 4-5 turns."},
]


def get_pokemon(index):
    return pokemon[index]


def get_type_multiplicator(attack, defense):
    return type_multiplicator[attack][defense]


def get_move(index):
    return move[index]


def main():
    return


if __name__ == "__main__":
    main()
